import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import { getProperties } from '../utils/contentful-helper'
import { useRouter } from 'next/router'
import { SUPPORTED_COUNTRIES, COUNTRY_STRINGS } from '../constants'

export const getStaticProps = async () => {
  const properties = await getProperties()

  return {
    props: { properties }
  }
}

export async function getStaticPaths() {
  return {
    paths: SUPPORTED_COUNTRIES.map(country => ({ params: { country } })),
    fallback: false
  }
}

export default function Home({ properties }) {
  const router = useRouter()
  const { country } = router.query

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>
        {country && <span>Had enough of {COUNTRY_STRINGS[country]}?</span>} Why
        not Work Somewhere Else?
      </h1>
      <p>Here is a list of places we have worked from and fully recommend:</p>
      <ul>
        {properties.map(({ title, urlSlug, sys: { id } }) => (
          <Link
            href={{
              pathname: '/properties/[slug]',
              query: { slug: urlSlug }
            }}
            key={id}
            passHref
          >
            <a>
              <li key={title}>{title}</li>
            </a>
          </Link>
        ))}
      </ul>
    </div>
  )
}
